### ISSUE TITLE
"Your rewriteRule is not ready to use." error on nginx

### ISSUE THREAD

**Issue by ChelonianEgghead** [Kanti/htmly-installer#29]
I'm running nginx 1.14.2 and PHP 7.4.8 on Debian 10 with Linux kernel 4.19.0-9 in a Vultr VPS. No matter what I try, I always get the error "Your rewriteRule is not ready to use." when using the installer, followed by this when I click "Install via tool":

```Fatal error: Uncaught Error: Class 'ZipArchive' not found in /var/www/html/htmly/installer.php:4366 Stack trace: #0 /var/www/html/htmly/installer.php(4342): Updater->unZip() #1 /var/www/html/htmly/installer.php(4578): Updater->update() #2 /var/www/html/htmly/installer.php(4565): Settings->install() #3 /var/www/html/htmly/installer.php(4533): Settings->runForm() #4 /var/www/html/htmly/installer.php(4589): Settings->__construct() #5 {main} thrown in /var/www/html/htmly/installer.php on line 4366```

Here's my nginx configuration file which is located at [/etc/nginx/sites-available/stephenvk.xyz](https://github.com/Kanti/htmly-installer/files/5029814/nginx-config.txt) and symlinked into the sites-enabled directory, and if you need any additional information about my server it should be listed here. http://stephenvk.xyz/info.php

Hope you can help, I'm looking forward to using a nice lightweight alternative to WordPress.

**Comment by Kanti** [comment]
Hi @ChelonianEgghead,

it looks like your PHP dose not have the extension zip.
See here on [Stackoverflow](https://stackoverflow.com/a/3872578/5440709) for more details.

I will close this issue as it has nothing to do with htmly-installer directly.
